name: Generate PDFs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          npm install -g markdown-pdf

      - name: Generate PDFs
        run: |
          for file in Engelska/*.md; do
            markdown-pdf "$file"
            mkdir -p "$(dirname "$file")/pdf"
            mv "${file%.md}.pdf" "$(dirname "$file")/pdf/"
          done

          for file in Svenska/*.md; do
            markdown-pdf "$file"
            mkdir -p "$(dirname "$file")/pdf"
            mv "${file%.md}.pdf" "$(dirname "$file")/pdf/"
          done

      - name: Commit and push PDFs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-generate PDFs" || true
          git push https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}