name: Convert MD to PDF

on:
  push:
    branches:
      - '**'
jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install pdflatex
        run: |
          sudo apt-get install -y texlive-xetex

      - name: Find and convert updated MD files to PDF
        run: |
          for file in $(git diff --name-only HEAD^ HEAD | grep '\.md$'); do
            pdf_file="${file%.md}.pdf"
            pdf_dir=$(dirname "$pdf_file")
            mkdir -p "$pdf_dir"
            pandoc -s "$file" -o "$pdf_file"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Convert MD to PDF"
          git push
