name: Generate PDFs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Generate PDFs
        run: |
          for file in Engelska/*.md; do
            pandoc "$file" -o "$(dirname "$file")/pdf/${file%.md}.pdf"
          done

          for file in Svenska/*.md; do
            pandoc "$file" -o "$(dirname "$file")/pdf/${file%.md}.pdf"
          done

      - name: Commit and push PDFs
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Auto-generate PDFs" || true
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
