name: Generate PDFs for CVs and Cover Letters

on:
  push:
    branches:
      - '**' # Trigger on any branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate PDFs for Engelska folder
      - name: Convert Markdown to PDF (Engelska)
        if: startsWith(github.ref, 'refs/heads/')
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Engelska
          output_dir: Engelska/pdf

      # Generate PDFs for Svenska folder
      - name: Convert Markdown to PDF (Svenska)
        if: startsWith(github.ref, 'refs/heads/')
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Svenska
          output_dir: Svenska/pdf

      - name: Verify Outputs
        run: |
          ls -l ./Engelska/pdf
          ls -l ./Svenska/pdf

      - name: Commit and Push PDFs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./Engelska/pdf ./Svenska/pdf
          git commit -m 'Add generated PDFs'
          git push
