name: Convert MD to PDF

on:
  push:
    branches:
      - main
jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install pdflatex
        run: |
          sudo apt-get install -y texlive-xetex

      - name: Convert Engelska MD to PDF
        run: |
          pandoc -s ./Engelska/Cover\ Letter.md -o ./Engelska/pdf/Cover\ Letter.pdf
          pandoc -s ./Engelska/CV.md -o ./Engelska/pdf/CV.pdf

      - name: Convert Svenska MD to PDF
        run: |
          pandoc -s ./Svenska/Cover\ Letter.md -o ./Svenska/pdf/Cover\ Letter.pdf
          pandoc -s ./Svenska/CV.md -o ./Svenska/pdf/CV.pdf

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Convert MD to PDF"
          git push

      - name: Upload PDFs to releases
        uses: actions/upload-artifact@v2
        with:
          name: pdf-artifacts
          path: ./Svenska/pdf/, ./Engelska/pdf/
          if-no-files-found: error
