name: Convert Markdown to PDF and Commit

on:
  push:
    branches:
      - '**'  # Trigger on any branch
  workflow_dispatch:

jobs:
  convert-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history for committing changes

      # Convert Markdown files in Engelska
      - name: Generate PDFs for Engelska
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: Engelska
          output_dir: EngelskaPDF

      # Convert Markdown files in Svenska
      - name: Generate PDFs for Svenska
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: Svenska
          output_dir: SvenskaPDF

      # Commit and Push Changes
      - name: Commit and Push PDFs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add EngelskaPDF/*.pdf EngelskaPDF/*.html SvenskaPDF/*.pdf SvenskaPDF/*.html
          git commit -m "Generate PDFs for ${GITHUB_REF_NAME} [skip ci]" || echo "No changes to commit"
          git push origin "${GITHUB_REF_NAME}"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
